[build]
  base = "."
  publish = "dist/apps/web/browser"
  command = "npx nx run web:build"

[functions]
  directory = "apps/web/netlify/functions"
  node_bundler = "esbuild"

[functions."parse-diet"]
  # Max timeout for free tier is 26 seconds
  # For paid plans can go up to 15 minutes
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
